### ISSUE TITLE
Is paper publicly available? If yes, can you provide a link? Many thanks.

### ISSUE THREAD

**Issue by jiwei0921** [PanoAsh/PAV-SOD#1]

**Comment by YeeZ93** [comment]
Thanks for the attention to our work ! 

The paper is now under review and will not be publicly available recently, however our panoramic audiovisual SOD dataset (PAVS10K) is completely released.

We expect to continually make contributions to the SOD community and we will update the page once there is further  progress.


Many thanks!

**Comment by jiwei0921** [comment]
Thanks for your response. Finger crossed.
