### ISSUE TITLE
Question about the difference between PAVS10K and ASOD60k

### ISSUE THREAD

**Issue by JerryX1110** [PanoAsh/PAV-SOD#2]
Hi, thanks for your wanderful repo to share the paronamic video dataset. I am a little bit confused about the difference between PAVS10K and ASOD60k dataset. Also, could you please tell me where to download the ASOD60k dataset? Thanks! : )

**Comment by YeeZ93** [comment]
Hi, thanks for your attention to our work! 

If this work still interests you, please check and cite [our paper](https://dl.acm.org/doi/abs/10.1145/3565267).


Best,
Jun-Pu (Yi) Zhang

**Comment by YeeZ93** [comment]
To supplement, 

I have not checked the so-called [ASOD60K](https://arxiv.org/abs/2107.11629), please make un enquiry to the arXiv submitter [Ge-Peng Ji](https://github.com/GewelsJI) for details, or just ask [Deng-Ping Fan](https://github.com/DengPingFan) who may be responsible to that.

Best, 
Jun-Pu (Yi) Zhang

**Comment by YeeZ93** [comment]
@DengPingFan @GewelsJI

**Comment by JerryX1110** [comment]
Got it, thanks!

**Comment by aflyingnoob** [comment]
I am also confused about it, I search the paper of asod60k, the link in this paper refers to PAVS10K

**Comment by zhm284** [comment]
Hello, I would like to ask what formula is used to calculate the roll, yaw, and pitch in the dataset, which is their relationship with latitude and longitude
