### ISSUE TITLE
WAV files

### ISSUE THREAD

**Issue by zsevenj** [PanoAsh/PAV-SOD#4]
Hi, thanks for your share the PAVSOD dataset. 
Could you share the 'ambisonics_trimmed' (.wav) audio files, please? 
It seems to have 4 channels in data.py. I tried to convert the .mp4 file to .wav file, but I only got 2 channels
Thanks!

**Comment by YeeZ93** [comment]
Hi,

Thanks so much for your interest towards our work! The WAV files can be downloaded at https://drive.google.com/file/d/1-jqDArcm8vBhyku3Xb8HLopG1XmpAS13/view?usp=sharing . 

Best,
Yi

**Comment by zsevenj** [comment]
Thank you very much for your reply. In data.py, the wav file appears to have 4 channels. But I only got 1 channel in the test data you provided. Could you check it? Looking forward to your reply！

**Comment by YeeZ93** [comment]
Hi,

Please check the [Dataset Downloads Section](https://github.com/Jun-Pu/PAV-SOD#dataset-downloads) "The videos (with ambisonics) with default split can be downloaded from...", to download the ambisonics (4-channel ones) of each of the videos from both training/testing sets. You may need an [audio extractor](https://audio-extractor.net/) to acquire the unified 4-channel WAVs. 

In our data.py, we initially load the 4-channel audio file (if the specific video does have one), yet all audio files are then unified into 1-channel (mono sound) to be fed to our CAV-Net. 

We will update the [link](https://drive.google.com/file/d/1-jqDArcm8vBhyku3Xb8HLopG1XmpAS13/view) with the WAVs of both modalities (mono&ambisonics). Thanks


Best,
Yi

**Comment by zsevenj** [comment]
Thanks for your response.
